/* isqrt tool — do not edit this file; the task is the Makefile. */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

static long isqrt(long n)
{
    assert(n >= 0 && "isqrt: negative input");
    if (n < 0)
        return -1; /* reached only when assertions are compiled out */
    long r = 0;
    while ((r + 1) * (r + 1) <= n)
        r++;
    return r;
}

int main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: app N\n");
        return 2;
    }
#ifdef DEBUG
    fprintf(stderr, "debug: parsing '%s'\n", argv[1]);
#endif
    long n = strtol(argv[1], NULL, 10);
    long r = isqrt(n);
    if (r < 0) {
        puts("no result");
        return 1;
    }
    printf("%ld\n", r);
    return 0;
}
